# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
lineone: <a href="http://wiki.hcr2.info">Wiki</a> - <a href="https://fingersoft.com/news/">FS News</a> - <a href="https://mobile.twitter.com/HCR_Official_">FS Tweets</a> - <a href="https://www.youtube.com/results?search_query=hill+climb+racing+2+hcr2">YouTube</a>  
linethree: <a href="http://fw.hcr2.info">Friendly Wars</a> - <a href="http://tw.hcr2.info">Tractor Wars</a> - <a href="/vehicles/">Vehicles</a>
linetwo: <a href="./blog.html">Log</a> - <a href="./tips.html">Tips</a> - <a href="./chests.html">Chests</a> - <a href="./memes.html">Memes</a> - <a href="./gm.html">GM</a> - <a href="./faq.html">FAQ</a>
buttonone:  <a href=".\#best-distance-parts-by-vehicle">Adventure <strong>Parts</strong></a> 
buttontwo: <a href=".\#tracks-by-map-type-and-distance">Cup <strong>Tracks</strong></a> 
buttonthree: <a href=".\#daily-checklist">Daily <strong>Checklist</strong></a>           
footerone:  <a href="#top"><img src="https://cdn.discordapp.com/attachments/806343355264401478/820076457690398751/GBG-team-logo-125.png" alt="Gas Brake Go"/></a>
footertwo:  <a href="mailto:dadahcr2@gmail.com">dadahcr2@gmail.com</a> ~ dada#1710 ~ <a href="https://discord.gg/w29PA2H3M4">discord server</a> ~ <a href="https://rentry.co/hcom1">Comment?</a>
footerthree: Portions of the materials used are trademarks and/or copyrighted works of Fingersoft Ltd. All rights reserved by Fingersoft. This material is not official and is not endorsed by Fingersoft.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
logo: "/assets/images/4C035FA1-738A-4AA3-AD37-E81B96BD5967.jpeg"
title: "HCR2 REFERENCE"
email: dadahcr2@gmail.com
description: "HCR2 Reference Information"
twitter_username: 
github_username: 
minimal_mistakes_skin: default
search: false
search_full_content: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /_pages/page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "dada#1710"
  avatar : "/assets/images/734B83DB-D390-4091-AECD-0DCA7DB6894F.png"
  bio    : <a href="http://wiki.hcr2.info">Wiki</a>•<a href="https://fingersoft.com/news/">FS News</a>•<a href="https://mobile.twitter.com/HCR_Official_">FS Tweets</a><BR><a href="https://www.youtube.com/results?search_query=hill+climb+racing+2+hcr2">YouTube</a>•<a href="/memes/">Memes</a>•<a href="/chests/">Chests</a><br><a href="/">Info</a>•<a href="/blog/">Log</a>•<a href="/tips/">Tips</a>•<a href="/gm/">GM</a>•<a href="/faq/">FAQ</a>
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:dadahcr2@gmail.com"
    - label: "PE Server"
      icon: "fab fa-discord"
 #     icon: "fas fa-comments"
      url: "https://discord.gg/FZPnQbxZTQ"
 # - label: "Twitter"
   #  icon: "fab fa-fw fa-twitter-square"
  #    url: "https://twitter.com/"
  #  - label: "GitHub"
   #   icon: "fab fa-fw fa-github"
  #    url: "https://github.com/"
  #  - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:dadahcr2@gmail.com"
    - label: "PE Server"
      icon: "fab fa-discord"
#      icon: "fas fa-comments"
      url: "https://discord.gg/FZPnQbxZTQ"
 #    - label: "Twitter"
 #     icon: "fab fa-fw fa-twitter-square"
 #     url: "https://twitter.com/"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/"
#    - label: "Instagram"
 #     icon: "fab fa-fw fa-instagram"
 #     url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      
        
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

atom_feed:
  hide: true
